[package]
name = "moonrun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["cargo"] }
wasmtime = "17.0.0"

[profile.release]
lto = true
